#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Penpot Desktop – Frontend Build Script
# Clones the Penpot repo, builds the frontend, and prepares
# the static assets for Tauri.
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
PENPOT_DIR="$PROJECT_DIR/penpot-repo"
FRONTEND_DIR="$PENPOT_DIR/frontend"
OUTPUT_DIR="$PROJECT_DIR/src/penpot"

PENPOT_REPO="https://github.com/penpot/penpot.git"
PENPOT_BRANCH="${PENPOT_BRANCH:-2.14.2}"  # Match design.penpot.app version. Override with env var.

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERR]${NC}   $*"; exit 1; }

# ── Check prerequisites ──────────────────────────────────────
check_prereqs() {
    info "Checking prerequisites..."

    command -v git     >/dev/null 2>&1 || err "git not found. Please install."
    command -v node    >/dev/null 2>&1 || err "node not found. Node.js ≥18 required."
    command -v pnpm    >/dev/null 2>&1 || err "pnpm not found. Install with: npm install -g pnpm"
    command -v java    >/dev/null 2>&1 || err "java not found. JDK ≥21 required for ClojureScript."
    JAVA_VERSION=$(java -version 2>&1 | head -1 | sed -E 's/.*"([0-9]+).*/\1/')
    if [ "$JAVA_VERSION" -lt 21 ] 2>/dev/null; then
        err "JDK ≥21 required, found: Java $JAVA_VERSION. Install e.g. with: brew install openjdk@21"
    fi
    command -v clojure >/dev/null 2>&1 || err "clojure CLI not found. https://clojure.org/guides/install_clojure"

    NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
    if [ "$NODE_VERSION" -lt 18 ]; then
        err "Node.js ≥18 required, found: $(node -v)"
    fi

    ok "All prerequisites met."
}

# ── Clone or update Penpot repo ──────────────────────────────
clone_penpot() {
    if [ -d "$PENPOT_DIR/.git" ]; then
        info "Penpot repo exists, updating..."
        cd "$PENPOT_DIR"
        git fetch origin
        git checkout "$PENPOT_BRANCH"
        git pull origin "$PENPOT_BRANCH"
        cd "$PROJECT_DIR"
    else
        info "Cloning Penpot repo (may take a few minutes)..."
        git clone --depth 1 --branch "$PENPOT_BRANCH" "$PENPOT_REPO" "$PENPOT_DIR"
    fi
    ok "Penpot repo ready: $PENPOT_DIR"
}

# ── Build the frontend ───────────────────────────────────────
build_frontend() {
    info "Building Penpot frontend..."

    # Install Node dependencies (frontend has its own pnpm-workspace.yaml)
    info "Installing Node dependencies..."
    cd "$FRONTEND_DIR"
    pnpm install

    # Resolve Clojure dependencies
    info "Resolving Clojure dependencies..."
    clojure -P || true

    export NODE_ENV=production
    export VERSION="${PENPOT_BRANCH}"
    export VERSION_TAG="${PENPOT_BRANCH}"

    # Patch out JVM flags unsupported on JDK <23
    if [[ "$JAVA_VERSION" -lt 23 ]] 2>/dev/null; then
        info "Patching deps.edn for JDK $JAVA_VERSION (removing --sun-misc-unsafe-memory-access)..."
        sed -i.bak 's/"--sun-misc-unsafe-memory-access=allow"//' "$FRONTEND_DIR/deps.edn"
    fi

    # Step 0: Ensure render_wasm shared.js exists (generated by render-wasm build)
    SHARED_JS="$FRONTEND_DIR/src/app/render_wasm/api/shared.js"
    if [ ! -f "$SHARED_JS" ]; then
        if [ "$PENPOT_BRANCH" = "staging" ] || [ "$PENPOT_BRANCH" = "main" ]; then
            # For staging/main: download from Penpot Cloud
            info "Downloading shared.js from Penpot Cloud..."
            curl -sL "https://design.penpot.app/js/render-wasm.js" -o /tmp/_render_wasm_dl.js
            # Extract the shared constants from the render-wasm module
            # The actual shared.js is embedded in the build, download directly
            PENPOT_CDN="https://design.penpot.app"
            # Try to get shared.js from the worker build which includes it
            curl -sL "$PENPOT_CDN/js/worker/render.js" -o /tmp/_worker_render.js 2>/dev/null
            if [ -s /tmp/_worker_render.js ]; then
                ok "Using worker render.js as shared.js source."
            fi
            # shared.js is a build artifact not served directly, try Docker devenv as fallback
            if docker exec penpot-devenv-main test -d /home/penpot/penpot 2>/dev/null; then
                SHARED_SRC=$(docker exec penpot-devenv-main find /home/penpot/penpot/render-wasm/target -name "render_wasm_shared.js" 2>/dev/null | head -1)
                if [ -n "$SHARED_SRC" ]; then
                    docker cp "penpot-devenv-main:$SHARED_SRC" "$SHARED_JS"
                    ok "shared.js copied from devenv."
                fi
            fi
            if [ ! -f "$SHARED_JS" ]; then
                warn "shared.js not available. Creating empty stub..."
                echo "// render_wasm shared stub" > "$SHARED_JS"
            fi
        else
            # For develop/tags: try Docker devenv
            info "shared.js not found, trying to copy from Docker devenv..."
            if docker exec penpot-devenv-main test -d /home/penpot/penpot 2>/dev/null; then
                SHARED_SRC=$(docker exec penpot-devenv-main find /home/penpot/penpot/render-wasm/target -name "render_wasm_shared.js" 2>/dev/null | head -1)
                if [ -n "$SHARED_SRC" ]; then
                    docker cp "penpot-devenv-main:$SHARED_SRC" "$SHARED_JS"
                    ok "shared.js copied from devenv."
                else
                    warn "shared.js not found in devenv. Creating empty stub..."
                    echo "// render_wasm shared stub" > "$SHARED_JS"
                fi
            else
                warn "Docker devenv not available. Creating empty stub for shared.js..."
                echo "// render_wasm shared stub" > "$SHARED_JS"
            fi
        fi
    fi

    # Patch store.cljs: add desktop selection bridge
    # (no-op when __penpotDesktopOnSelection is not defined, i.e. in browser)
    STORE_CLJS="$FRONTEND_DIR/src/app/main/store.cljs"
    if ! grep -q "desktop-selection" "$STORE_CLJS" 2>/dev/null; then
        info "Patching store.cljs with desktop selection bridge..."
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' '/::ongoing-tasks/,/(constantly false)))/{ /(constantly false)))/a\
\
;; Desktop selection bridge — calls JS callback when selection changes\
(add-watch state ::desktop-selection\
  (fn [_ _ old-state new-state]\
    (let [old-sel (get-in old-state [:workspace-local :selected])\
          new-sel (get-in new-state [:workspace-local :selected])]\
      (when (not= old-sel new-sel)\
        (when-let [cb (obj/get js/window "__penpotDesktopOnSelection")]\
          (cb (count new-sel)))))))\

}' "$STORE_CLJS"
        else
            sed -i '/::ongoing-tasks/,/(constantly false)))/{ /(constantly false)))/a\
\
;; Desktop selection bridge — calls JS callback when selection changes\
(add-watch state ::desktop-selection\
  (fn [_ _ old-state new-state]\
    (let [old-sel (get-in old-state [:workspace-local :selected])\
          new-sel (get-in new-state [:workspace-local :selected])]\
      (when (not= old-sel new-sel)\
        (when-let [cb (obj/get js/window "__penpotDesktopOnSelection")]\
          (cb (count new-sel)))))))\

}' "$STORE_CLJS"
        fi
        ok "store.cljs patched."
    else
        info "store.cljs already patched, skipping."
    fi

    # Step 1: Compile ClojureScript → JavaScript (main + worker)
    info "Compiling ClojureScript → JavaScript (production)..."
    pnpm run clear:shadow-cache || true
    pnpm run build:app:main

    # Step 2: Bundle external JS libs with esbuild
    info "Bundling JS libs..."
    pnpm run build:app:libs

    # Step 3: Compile SCSS, templates, sprites, translations, polyfills
    info "Compiling assets (CSS, templates, sprites, translations)..."
    pnpm run build:app:assets

    # Step 4: Download render-wasm
    WASM_DIR="$FRONTEND_DIR/resources/public/js"
    mkdir -p "$WASM_DIR/worker"

    if docker exec penpot-devenv-main test -f /home/penpot/penpot/frontend/resources/public/js/render-wasm.wasm 2>/dev/null; then
        info "Copying render-wasm from Docker devenv..."
        docker cp penpot-devenv-main:/home/penpot/penpot/frontend/resources/public/js/render-wasm.wasm "$WASM_DIR/render-wasm.wasm"
        docker cp penpot-devenv-main:/home/penpot/penpot/frontend/resources/public/js/render-wasm.js "$WASM_DIR/render-wasm.js"
        docker cp penpot-devenv-main:/home/penpot/penpot/frontend/resources/public/js/worker/render.js "$WASM_DIR/worker/render.js" 2>/dev/null || true
        ok "render-wasm copied from devenv."
    else
        info "Downloading render-wasm from Penpot Cloud..."
        PENPOT_CDN="https://design.penpot.app"
        curl -sL "$PENPOT_CDN/js/render-wasm.js"   -o "$WASM_DIR/render-wasm.js"
        curl -sL "$PENPOT_CDN/js/render-wasm.wasm"  -o "$WASM_DIR/render-wasm.wasm"
        curl -sL "$PENPOT_CDN/js/worker/render.js"  -o "$WASM_DIR/worker/render.js"
        ok "render-wasm downloaded from Penpot Cloud."
    fi

    ok "Frontend build complete."
    cd "$PROJECT_DIR"
}

# ── Copy built assets to Tauri frontend dir ──────────────────
prepare_assets() {
    info "Copying build assets to $OUTPUT_DIR ..."
    rm -rf "$OUTPUT_DIR"
    mkdir -p "$OUTPUT_DIR"

    # The built frontend lands in frontend/resources/public/
    BUILT_DIR="$FRONTEND_DIR/resources/public"

    if [ ! -d "$BUILT_DIR" ]; then
        err "Build output not found! Expected in: $FRONTEND_DIR/resources/public/"
    fi

    cp -r "$BUILT_DIR/"* "$OUTPUT_DIR/"

    # Inject our config loader into index.html
    inject_config_loader

    ok "Assets ready in $OUTPUT_DIR"
    echo ""
    info "File count: $(find "$OUTPUT_DIR" -type f | wc -l)"
    info "Total size: $(du -sh "$OUTPUT_DIR" | cut -f1)"
}

# ── Inject runtime config loader ─────────────────────────────
inject_config_loader() {
    local INDEX="$OUTPUT_DIR/index.html"

    if [ ! -f "$INDEX" ]; then
        warn "index.html not found, skipping config injection."
        return
    fi

    info "Injecting runtime config loader into index.html..."

    # Insert our config script before the closing </head> tag
    # macOS sed needs '' for -i, Linux doesn't
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' 's|</head>|<script src="/__penpot_desktop_config.js"></script>\
</head>|' "$INDEX"
    else
        sed -i 's|</head>|<script src="/__penpot_desktop_config.js"></script>\n</head>|' "$INDEX"
    fi

    ok "Config loader injected."
}

# ── Main ─────────────────────────────────────────────────────
main() {
    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║   Penpot Desktop – Frontend Build        ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
    echo ""

    check_prereqs
    clone_penpot
    build_frontend
    prepare_assets

    echo ""
    echo -e "${GREEN}✓ Build successful!${NC}"
    echo ""
    echo "  Next steps:"
    echo "    bun run tauri:dev    # For testing"
    echo "    bun run tauri:build  # For production"
    echo ""
}

main "$@"
